In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
college_df = pd.read_csv(r'/content/drive/My Drive/DATA 606/Final.csv')

In [ ]:
college_df.head()

Unnamed: 0  Unnamed: 0.1  ...  relative_value_dollar_2017  national_rank
0           0            62  ...                      115.34           71.0
1           1            64  ...                      115.34           71.0
2           2            69  ...                      115.34           71.0
3           3            72  ...                      115.34           71.0
4           4            73  ...                      115.34           71.0

[5 rows x 30 columns]

In [ ]:
del college_df['Unnamed: 0.1']
del college_df['Unnamed: 0']

In [ ]:
college_df.isna().sum()

UNITID                         0
OPEID6                         0
INSTNM                         0
CONTROL                        0
MAIN                           0
CIPCODE                        0
CIPDESC                        0
CREDLEV                        0
CREDDESC                       0
COUNT                          0
DEBTMEDIAN                     0
DEBTPAYMENT10YR                0
DEBTMEAN                       0
TITLEIVCOUNT                   0
EARNINGSCOUNT                  0
MD_EARN_WNE                    0
IPEDSCOUNT1                   10
IPEDSCOUNT2                   20
CITY                           0
STATE                          0
ZIP                            0
TUITFTE                        0
INEXPFTE                       0
ACCREDAGENCY                   0
FTFTPCTPELL                   68
cost_living_index_2020         0
relative_value_dollar_2017     0
national_rank                  0
dtype: int64

Q1. It is a general belief that studying at the main campus will give the students better work opportunities and leave them with less debt. Is this true?

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import r2_score,mean_squared_error
import matplotlib.pyplot as plt

In [ ]:
X=college_df[['MAIN','MD_EARN_WNE', 'national_rank']]

#X=college_df[['MAIN','MD_EARN_WNE', 'national_rank','DEBTMEAN']]
#X=college_df[['MAIN','MD_EARN_WNE', 'national_rank','DEBTMEAN','CREDLEV','COUNT']]

In [ ]:
X.head()

MAIN  MD_EARN_WNE  national_rank
0     1        26300           71.0
1     1        56900           71.0
2     1        50500           71.0
3     1        57200           71.0
4     1        43700           71.0

In [ ]:
Y=college_df['DEBTMEDIAN']

In [ ]:
Y.head()

0    21474
1    27750
2    22601
3    57346
4    28218
Name: DEBTMEDIAN, dtype: int64

In [ ]:
# Split the data into Trainging and Testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size = 0.30,random_state =42)

In [ ]:
svr_model=SVR()

In [ ]:
svr_model.fit(X_train,Y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred=svr_model.predict(X_test)
y_pred

array([24546.75117567, 24502.19652251, 24553.35971021, ...,
       25196.67364112, 24478.45519005, 24580.37902642])

Without main campus feature

In [ ]:
X1=college_df[['MD_EARN_WNE', 'national_rank']]

#X1=college_df[['MD_EARN_WNE', 'national_rank','DEBTMEAN']]
#X1=college_df[['MD_EARN_WNE', 'national_rank','DEBTMEAN','CREDLEV','COUNT']]

In [ ]:
X1.head()

MD_EARN_WNE  national_rank
0        26300           71.0
1        56900           71.0
2        50500           71.0
3        57200           71.0
4        43700           71.0

In [ ]:
Y1=college_df['DEBTMEDIAN']

In [ ]:
Y1.head()

0    21474
1    27750
2    22601
3    57346
4    28218
Name: DEBTMEDIAN, dtype: int64

In [ ]:
# Split the data into Trainging and Testing sets
X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X1, Y1,test_size = 0.30,random_state =42)

In [ ]:
svr_model1=SVR()

In [ ]:
svr_model1.fit(X_train1,Y_train1)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred1=svr_model1.predict(X_test1)
y_pred1

array([24546.13469257, 24496.5318757 , 24552.74359428, ...,
       25240.74690051, 24471.87532837, 24584.52413507])

Evaluating models using the mean squared error. The mean squared error tells you how close a regression line is to a set of points.

In [ ]:
#Model evaluation: main campus feature included
mse=mean_squared_error(Y_test,y_pred)
rsme=np.sqrt(mse)
rsme

32926.05050394414

In [ ]:
#Model evaluation: without main campus feature
mse1=mean_squared_error(Y_test1,y_pred1)
rsme1=np.sqrt(mse1)
rsme1

32920.34538011089

The larger the number the larger the error. Error in this case is the difference between the observed values and the predicted ones.

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(Y_test, y_pred)

-0.07585297951746806

In [ ]:
r2_score(Y_test1, y_pred1)

-0.07548018395752032

R score is negative.. the model is arbitrarily bad

SVR model does not seem to support our data. The performance of the model is very bad. I will be trying other regression models in the next steps.

Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
linear_model=LinearRegression()

In [ ]:
linear_model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=linear_model.predict(X_test)
y_pred

array([25415.78631222, 20402.31876874, 24513.52041616, ...,
       69495.99182153, 19007.40899602, 16454.01081811])

In [ ]:
#Without main campus

In [ ]:
linear_model1=LinearRegression()

In [ ]:
linear_model1.fit(X_train1,Y_train1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred1=linear_model1.predict(X_test1)
y_pred1

array([25415.78631222, 20402.31876874, 24513.52041616, ...,
       69495.99182153, 19007.40899602, 16454.01081811])

Evaluating models using the mean squared error. The mean squared error tells you how close a regression line is to a set of points.

In [ ]:
#Model evaluation: main campus feature included
mse=mean_squared_error(Y_test,y_pred)
rsme=np.sqrt(mse)
rsme

4525.69285518737

In [ ]:
#Model evaluation: without main campus feature
mse1=mean_squared_error(Y_test1,y_pred1)
rsme1=np.sqrt(mse1)
rsme1

4525.692855187361

The larger the number the larger the error. Error in this case is the difference between the observed values and the predicted ones.<br>
Here, the values 4525 indicates that the predicted debt has a range of + or - 4525 of the original debt value. I will not say my model that the model is at its best performance but after all the combinations I tried, this is the best performance.

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(Y_test, y_pred)

0.9796743801016072

In [ ]:
r2_score(Y_test1, y_pred1)

0.9796743801016073

R-squared is how well the regression model fits the observed data. Higher r-squared indicates a better fit for the model.

In [ ]:
X.head()

MAIN  MD_EARN_WNE  national_rank
0     1        26300           71.0
1     1        56900           71.0
2     1        50500           71.0
3     1        57200           71.0
4     1        43700           71.0

In [ ]:
#residual plot : do it

In [ ]:
Y.head()

0    21474
1    27750
2    22601
3    57346
4    28218
Name: DEBTMEDIAN, dtype: int64

In [ ]:
college_df.head()

UNITID  OPEID6  ... relative_value_dollar_2017 national_rank
0  100663.0    1052  ...                     115.34          71.0
1  100663.0    1052  ...                     115.34          71.0
2  100663.0    1052  ...                     115.34          71.0
3  100663.0    1052  ...                     115.34          71.0
4  100663.0    1052  ...                     115.34          71.0

[5 rows x 28 columns]

In [ ]:
college_df.columns

Index(['UNITID', 'OPEID6', 'INSTNM', 'CONTROL', 'MAIN', 'CIPCODE', 'CIPDESC',
       'CREDLEV', 'CREDDESC', 'COUNT', 'DEBTMEDIAN', 'DEBTPAYMENT10YR',
       'DEBTMEAN', 'TITLEIVCOUNT', 'EARNINGSCOUNT', 'MD_EARN_WNE',
       'IPEDSCOUNT1', 'IPEDSCOUNT2', 'CITY', 'STATE', 'ZIP', 'TUITFTE',
       'INEXPFTE', 'ACCREDAGENCY', 'FTFTPCTPELL', 'cost_living_index_2020',
       'relative_value_dollar_2017', 'national_rank'],
      dtype='object')