In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
college_df = pd.read_csv(r'/content/drive/My Drive/DATA 606/Final.csv')

In [4]:
college_df.head()

Unnamed: 0  Unnamed: 0.1  ...  relative_value_dollar_2017  national_rank
0           0            62  ...                      115.34           71.0
1           1            64  ...                      115.34           71.0
2           2            69  ...                      115.34           71.0
3           3            72  ...                      115.34           71.0
4           4            73  ...                      115.34           71.0

[5 rows x 30 columns]

In [5]:
del college_df['Unnamed: 0.1']
del college_df['Unnamed: 0']

In [6]:
college_df.isna().sum()

UNITID                         0
OPEID6                         0
INSTNM                         0
CONTROL                        0
MAIN                           0
CIPCODE                        0
CIPDESC                        0
CREDLEV                        0
CREDDESC                       0
COUNT                          0
DEBTMEDIAN                     0
DEBTPAYMENT10YR                0
DEBTMEAN                       0
TITLEIVCOUNT                   0
EARNINGSCOUNT                  0
MD_EARN_WNE                    0
IPEDSCOUNT1                   10
IPEDSCOUNT2                   20
CITY                           0
STATE                          0
ZIP                            0
TUITFTE                        0
INEXPFTE                       0
ACCREDAGENCY                   0
FTFTPCTPELL                   68
cost_living_index_2020         0
relative_value_dollar_2017     0
national_rank                  0
dtype: int64

Q1. It is a general belief that studying at the main campus will give the students better work opportunities and leave them with less debt. Is this true?

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import r2_score,mean_squared_error
import matplotlib.pyplot as plt

My first model will have the main campus feature, median eranings and the national rank of the university as the inputs.

In [8]:
X=college_df[['MAIN','MD_EARN_WNE', 'national_rank']]

In [10]:
#Setting the target variable
Y=college_df['DEBTMEDIAN']

In [12]:
# Split the data into Trainging and Testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size = 0.30,random_state =42)

In [13]:
svr_model=SVR()

In [14]:
svr_model.fit(X_train,Y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [15]:
y_pred=svr_model.predict(X_test)
y_pred

array([24546.75117567, 24502.19652251, 24553.35971021, ...,
       25196.67364112, 24478.45519005, 24580.37902642])

I will be training my second model without using the main campus feature.

In [16]:
X_nomain=college_df[['MD_EARN_WNE', 'national_rank']]

In [18]:
Y_nomain=college_df['DEBTMEDIAN']

In [20]:
# Split the data into Trainging and Testing sets
X_train_nomain, X_test_nomain, Y_train_nomain, Y_test_nomain = train_test_split(X_nomain, Y_nomain,test_size = 0.30,random_state =42)

In [21]:
svr_model_nomain=SVR()

In [22]:
svr_model_nomain.fit(X_train_nomain,Y_train_nomain)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [23]:
y_pred_nomain=svr_model_nomain.predict(X_test_nomain)
y_pred_nomain

array([24546.13469257, 24496.5318757 , 24552.74359428, ...,
       25240.74690051, 24471.87532837, 24584.52413507])

Evaluating models using the mean squared error. The mean squared error tells you how close a regression line is to a set of points.

In [24]:
#Model evaluation: main campus feature included
mse=mean_squared_error(Y_test,y_pred)
rsme=np.sqrt(mse)
rsme

32926.05050394414

In [25]:
#Model evaluation: without main campus feature
mse_nomain=mean_squared_error(Y_test_nomain,y_pred_nomain)
rsme_nomain=np.sqrt(mse_nomain)
rsme_nomain

32920.34538011089

The larger the number the larger the error. Error in this case is the difference between the observed values and the predicted ones.

In [26]:
from sklearn.metrics import r2_score

In [27]:
r2_score(Y_test, y_pred)

-0.07585297951746806

In [28]:
r2_score(Y_test_nomain, y_pred_nomain)

-0.07548018395752032

R score is negative.. the model is arbitrarily bad

SVR model does not seem to support our data. The performance of the model is very bad. I will be trying other regression models in the next steps.

Linear Regression

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
#With main campus feature
linear_model=LinearRegression()

In [31]:
linear_model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
y_pred=linear_model.predict(X_test)
y_pred

array([25415.78631222, 20402.31876874, 24513.52041616, ...,
       69495.99182153, 19007.40899602, 16454.01081811])

In [33]:
#Without main campus feature
linear_model_nomain=LinearRegression()

In [34]:
linear_model_nomain.fit(X_train_nomain,Y_train_nomain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
y_pred_nomain=linear_model_nomain.predict(X_test_nomain)
y_pred_nomain

array([25415.78631222, 20402.31876874, 24513.52041616, ...,
       69495.99182153, 19007.40899602, 16454.01081811])

Evaluating models using the mean squared error. The mean squared error tells you how close a regression line is to a set of points.

In [36]:
#Model evaluation: main campus feature included
mse=mean_squared_error(Y_test,y_pred)
rsme=np.sqrt(mse)
rsme

4525.69285518737

In [37]:
#Model evaluation: without main campus feature
mse_nomain=mean_squared_error(Y_test_nomain,y_pred_nomain)
rsme_nomain=np.sqrt(mse_nomain)
rsme_nomain

4525.692855187361

The larger the number the larger the error. Error in this case is the difference between the observed values and the predicted ones.<br>
Here, the values 4525 indicates that the predicted debt has a range of + or - 4525 of the original debt value. I will not say my model that the model is at its best performance but after all the combinations I tried, this is the best performance.

In [38]:
from sklearn.metrics import r2_score

In [39]:
r2_score(Y_test, y_pred)

0.9796743801016072

In [40]:
r2_score(Y_test_nomain, y_pred_nomain)

0.9796743801016073

R-squared is how well the regression model fits the observed data. Higher r-squared indicates a better fit for the model. Here the linear regression models performed good.

Both the linear regression models have the same r2 score, which means the models predicted the debt values equally same. I will conclude saying, studying at the main campus does not really effect the amount of debt students are facing after graduation.